### ISSUE TITLE
Redstone z-fighting

### ISSUE THREAD

**Issue by 7777777-4547** [MoreMcmeta/emissive-plugin#4]
**Describe the bug**
Some emissive UV Face obstruct emissive others.
Redstone dust have Z-fighting.

**To reproduce**
1. Install Glowing Resourcepack
2. Join a world and make a dark environment
3. Place redstone torch and redstone dust

**Expected behavior**
Redstone torch has some Alpha UV face to obstruct other emissive thing's emissive face.
Redstone dust will have Z-fighting.

**Screenshots or videos**
![2023-08-25_03 07 17](https://github.com/MoreMcmeta/emissive-plugin/assets/83630775/253117d6-f548-4fd8-b07e-189634431562)
![2023-08-25_03 07 32](https://github.com/MoreMcmeta/emissive-plugin/assets/83630775/785b9749-3e8e-482b-8991-d1b7f5c93dc6)
![GIF 2023-8-25 3-09-28](https://github.com/MoreMcmeta/emissive-plugin/assets/83630775/423ce557-25c0-4b82-8ab1-b14311453a60)

**Which Minecraft versions does this bug affect?**
1.16.5

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [x] Fabric

**Mods list**
- dynamic-fps-2.0.2
- emissive-plugin-1.16.5-1.1.0-fabric
- entityculling-fabric-mc1.16.5-1.5.2
- fabric-api-0.42.0+1.16
- ferritecore-2.1.1-fabric
- indium-1.0.0+mc1.16.5
- iris-mc1.16.5-1.4.5
- lazydfu-0.1.2
- lithium-fabric-mc1.16.5-0.6.6
- memoryleakfix-fabric-pre1.17-1.1.1
- modernfix-fabric-5.7.1+mc1.16.5
- modmenu-1.16.23
- moremcmeta-1.16.5-4.2.0-fabric
- phosphor-fabric-mc1.16.2-0.8.0
- reeses_sodium_options-1.6.3+mc1.16.5-build.86
- sodium-extra-0.4.18+mc1.16.5-build.96
- sodium-fabric-mc1.16.5-0.2.0+build.4

**Resource pack**
- Glowing-OF_v0.2.0-1.16

**Additional context**
None

**Comment by soir20** [comment]
Thanks for the detailed report and images. I am going to split this into two threads because these are two separate issues. This will become the tracking issue for the z-fighting problem with redstone dust. #5 will become the tracking issue for the face obstruction issue.

**Comment by soir20** [comment]
Emissive plugin v1.1.1 has been released. This version contains a z-fighting fix pack with a custom block model that avoids the z-fighting issues. You'll need to enable this from your resource packs screen.

A special block model has to be used because Minecraft rendering has [issues](https://bugs.mojang.com/browse/MC-98523) with a bunch of translucent quads on top of each other like in the redstone model. If you look very closely, you'll notice that two pixels aren't visible in the new model that are visible in the old one; enlarging the model to include these two pixels causes a small rendering bug. It's not that noticeable, though. (The programmatic alternatives I tested didn't work well.)

Please report any other instances of z-fighting that you notice; these unfortunately have to be fixed individually. However, the redstone model seems fairly unique, so this is hopefully the only instance of the problem.

**Comment by soir20** [comment]
Version 2.0.0 has been released, which should fix this issue (without the need for the z-fighting fix pack). It will take a few minutes for the files to be approved on CurseForge. Please let me know if you encounter any issues in the new version.
