### ISSUE TITLE
Item Enchantment Glint and Item Entities Removing Rendering of Some Objects

### ISSUE THREAD

**Issue by RosiePies** [MoreMcmeta/emissive-plugin#7]
**Describe the bug**
Enchanted items have the whole texture face glinted.
Item entities' UV faces remove the rendering of water, item frames, and tile entities.

**To reproduce**
1. Join any world.
2. Place water, an item frame, or a tile entity.
3.  Throw an item (enchanted or not) on the ground in front of any object referenced in 2.

**Expected behavior**
Items' enchantment glint applies to opaque/translucent pixels of an item only.
Item entities do not obstruct rendering of water, item frames, or tile entities.

**Screenshots or videos**
![2023-10-03_02 52 26](https://github.com/MoreMcmeta/emissive-plugin/assets/130122260/39f27d9f-4c0d-4ee8-9ee1-8581d6c77159)
![2023-10-03_02 59 10](https://github.com/MoreMcmeta/emissive-plugin/assets/130122260/f61c2508-27ae-46bc-977c-9e7b12d8267a)
![2023-10-03_02 59 23](https://github.com/MoreMcmeta/emissive-plugin/assets/130122260/485eb4cc-d89f-4f25-bd1c-ad1ba440420d)

**Which Minecraft versions does this bug affect?**
1.20.1

**Mod loader**
Which mod loaders does this bug affect?
- [ Yes ] Forge - 47.1.3
- [ Maybe ] Fabric

**Mods list**
emissive-plugin-1.20.1-1.1.1-forge
moremcmeta-1.20.1-4.2.4-forge

**Resource pack**
None

**Comment by soir20** [comment]
MoreMcmeta uses translucent (partially transparent) emissive overlays. I believe this is an issue with vanilla Minecraft rendering when item models have translucent faces. You can cause this issue to happen in vanilla Minecraft by throwing stained glass panes on the ground near water. I will take a closer look to ensure that is the case.

I have noticed that this issue does not happen on Fabric, if you are able to use that instead of Forge.

I have some early plans for a v2 of this mod where overlays will not support translucence by default, but you can enable it on a per-overlay basis. That would help with a lot of these issues related to the translucent rendering, since almost all existing emissive packs don't need partial transparency. I don't have an ETA on that as it's still in a planning phase. The vast majority of issues reported have been translucence-related, so I'll likely create a separate tracking issue for this until v2 is released.

**Comment by soir20** [comment]
I've found the cause of the issue; it seems like the easiest way to fix this is likely to work on the v2 update. v2 looks to be simpler to implement than I expected, so hopefully this issue and other issues will all be resolved.

**Comment by soir20** [comment]
I have a working 2.x development version that fixes this issue. I am hoping for a release this weekend if no issues are discovered while I do more thorough testing.

**Comment by soir20** [comment]
Version 2.0.0 has been released, which should fix this issue. It will take a few minutes for the files to be approved on CurseForge. Please let me know if you encounter any issues in the new version.
